# Generated by Django 5.0 on 2023-12-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="remarks",
            field=models.TextField(default="a"),
            preserve_default=False,
        ),
    ]
