# Generated by Django 5.0 on 2024-02-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_description_product_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="URL",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
