# Generated by Django 5.0 on 2024-02-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_product_createddate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="CreatedDate",
            field=models.DateField(),
        ),
    ]
