# Generated by Django 5.0 on 2024-05-04 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_product_createddate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Description",
            field=models.TextField(
                default=datetime.datetime(
                    2024, 5, 4, 10, 49, 34, 689592, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="GitURL",
            field=models.URLField(
                default=datetime.datetime(
                    2024, 5, 4, 10, 49, 53, 221596, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="Image",
            field=models.ImageField(
                default=datetime.datetime(
                    2024, 5, 4, 10, 49, 56, 296407, tzinfo=datetime.timezone.utc
                ),
                upload_to="",
            ),
            preserve_default=False,
        ),
    ]
