# .github/workflows/deploy.yml

name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade --user

      - name: Install application dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Collect static files
        run: |
          python manage.py collectstatic --noinput

      - name: Deploy static files
        env:
          STATIC_ROOT: ${{ github.workspace }}/static
        run: |
          aws s3 sync --delete $STATIC_ROOT s3://$EB_BUCKET/static/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_REGION: ap-southeast-2
          APPLICATION_NAME: donthackmepls
          ENVIRONMENT_NAME: Donthackmepls-env
        run: |
          export PATH=$PATH:$HOME/.local/bin
          eb init $APPLICATION_NAME --platform python --region $AWS_REGION
          eb deploy $ENVIRONMENT_NAME --staged
